#!/bin/sh

. /home/haider/wordpress-5.8.2-0/scripts/setenv.sh

exec /home/haider/wordpress-5.8.2-0/php/sbin/.php-fpm.bin -y /home/haider/wordpress-5.8.2-0/php/etc/php-fpm.conf -p /home/haider/wordpress-5.8.2-0/php/var/ -c /home/haider/wordpress-5.8.2-0/php/etc/php.ini "$@"
